services:

  mongo:
    image: mongo
    container_name: mongo_db_test
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mydatabase
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    container_name: mongo_express_test
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongo:27017/mydatabase?authSource=admin
    depends_on:
      - mongo
    networks:
      - my-network

volumes:
  mongo:

networks:
  my-network:
    driver: bridge